using AutoMapper;
using Entities.Concrete;
using Entities.DTOs.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Business.Helper.AutoMapper
{
    public class UserMapper : Profile
    {
        public UserMapper()
        {
            CreateMap<User, UserListDTO>()
                .ForMember(dest => dest.RoleName, opt => opt.MapFrom(src => src.UserRoles.FirstOrDefault().Role.RoleName))
                .ReverseMap();

           // CreateMap<User, UserListDTO>().ReverseMap();

            CreateMap<User, UpdateUserDTO>().ReverseMap();
            CreateMap<AddUserDTO, User>()
                 .ForMember(dest => dest.Id, opt => opt.Ignore()) // Ignore mapping for Id (auto-generated by the database)
                 .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => DateTime.Now))
                 .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => DateTime.Now));
                



        }
    }
}
